CREATE TABLE Patient (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    dob DATE,
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20),
    address VARCHAR2(200),
    medical_history CLOB,
    allergies CLOB
);

CREATE TABLE Doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    specialization VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20)
);

CREATE TABLE Appointment (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    doctor_id NUMBER,
    appointment_date DATE,
    reason VARCHAR2(200),
    telemedicine_link VARCHAR2(200),
    status VARCHAR2(20),
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id)
);

CREATE TABLE Medicine (
    medicine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    stock_level NUMBER,
    dosage VARCHAR2(50),
    description VARCHAR2(200)
);

CREATE TABLE Prescription (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    doctor_id NUMBER,
    medicine_id NUMBER,
    prescription_date DATE,
    dosage VARCHAR2(50),
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id),
    FOREIGN KEY (medicine_id) REFERENCES Medicine(medicine_id)
);

CREATE TABLE IoT_Monitoring (
    monitor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    heart_rate NUMBER,
    blood_pressure VARCHAR2(20),
    timestamp DATE,
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id)
);

CREATE TABLE Employee (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    position VARCHAR2(100),
    salary NUMBER(10,2),
    hire_date DATE
);

CREATE TABLE Payroll (
    payroll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    payment_date DATE,
    amount NUMBER(10,2),
    FOREIGN KEY (employee_id) REFERENCES Employee(employee_id)
);
