-- Patient Table
CREATE TABLE Patient (
    patient_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    nationality VARCHAR2(50),
    gender VARCHAR2(10),
    address VARCHAR2(100),
    dob DATE,
    phone NUMBER(10),
    email VARCHAR2(50) UNIQUE
);

-- Doctor Table
CREATE TABLE Doctor (
    doctor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    specialization VARCHAR2(50),
    phone NUMBER(10),
    email VARCHAR2(50) UNIQUE
);

-- Appointment Table
CREATE TABLE Appointment (
    appointment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    doctor_id NUMBER,
    appointment_date DATE NOT NULL,
    reason VARCHAR2(100),
    CONSTRAINT fk_patient FOREIGN KEY (patient_id) REFERENCES Patient(patient_id),
    CONSTRAINT fk_doctor FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id)
);

-- Medicine Table
CREATE TABLE Medicine (
    med_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    med_name VARCHAR2(50) NOT NULL,
    dosage VARCHAR2(20),
    price NUMBER(6,2)
);

-- Prescribed_Med Table (junction between Patient and Medicine)
CREATE TABLE Prescribed_Med (
    med_prescription_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    patient_id NUMBER,
    med_id NUMBER,
    dosage VARCHAR2(50),
    prescription_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_patient_presc FOREIGN KEY (patient_id) REFERENCES Patient(patient_id),
    CONSTRAINT fk_med_presc FOREIGN KEY (med_id) REFERENCES Medicine(med_id)
);

-- Employee Table
CREATE TABLE Employee (
    employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    role VARCHAR2(50),
    department VARCHAR2(50),
    hire_date DATE DEFAULT SYSDATE,
    salary NUMBER(8,2) CHECK (salary > 0)
);

-- Payroll Table
CREATE TABLE Payroll (
    payroll_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    salary NUMBER(10),
    bonuses NUMBER(8,2),
    deductions NUMBER(8,2),
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES Employee(employee_id)
);